import { randomBytes } from 'node:crypto'

const TELEMETRY_PREFIX = 'atl_sk_'

/** Fixed length (in chars) of a base64url-encoded 16-byte credential id — see `generateTelemetryToken`. */
const CRED_ID_LENGTH = 22

export interface ParsedTelemetryToken {
  credId: string
  secret: string
}

function randomSecret(bytes: number): string {
  return randomBytes(bytes).toString('base64url')
}

/**
 * Generates a fresh telemetry credential id + token together, since the
 * token format (`atl_sk_<credId>_<secret>`) depends on `credId` having a
 * fixed, known length — parsing relies on that fixed length rather than
 * splitting on the last `_`, because both `credId` and `secret` are
 * base64url and may themselves contain `_`.
 */
export function generateTelemetryToken(): { credId: string; token: string } {
  const credId = randomBytes(16).toString('base64url')
  const token = `${TELEMETRY_PREFIX}${credId}_${randomSecret(24)}`
  return { credId, token }
}

/** Parses `atl_sk_<credId>_<secret>`. Returns `undefined` for anything else (including admin tokens). */
export function parseTelemetryToken(token: string): ParsedTelemetryToken | undefined {
  if (!token.startsWith(TELEMETRY_PREFIX)) return undefined
  const rest = token.slice(TELEMETRY_PREFIX.length)
  const credId = rest.slice(0, CRED_ID_LENGTH)
  const separator = rest[CRED_ID_LENGTH]
  const secret = rest.slice(CRED_ID_LENGTH + 1)
  if (credId.length !== CRED_ID_LENGTH || separator !== '_' || secret.length === 0) return undefined
  return { credId, secret }
}

// Admin tokens (`atl_admin_<name>_<secret>`) are never generated by the server
// at runtime — they live only in the `ATEL_ADMIN_CREDENTIALS` env var, minted
// out-of-band. There is deliberately no `parseAdminToken` either:
// `resolveAdminCredential` matches presented tokens against the configured
// list by direct comparison, never by parsing a name back out of the token
// (`name` may itself contain `_`, which would make that ambiguous).
